/**
 * Coexistence tests: parse() reads legacy SEPA formats into the same model.
 *
 * pain.001.001.03: generated via the `sepa` devDependency (same library used in
 * differential.test.ts). Verifies that parse() normalises it to type="pain.001"
 * with correct model fields.
 *
 * pain.008.001.02: hand-built minimal valid XML string, first validated against
 * the .02 XSD (oracle), then parsed and model fields checked.
 *
 * validateXsd tests confirm all four namespaces are handled by the validator.
 */

import { describe, it, expect } from 'vitest'
import SEPA from 'sepa'
import { parse } from '../src/parser/parser.js'
import { validateXsd } from '../src/xsd.js'
import { writeCreditTransfer } from '../src/writer/writer.js'
import { euros } from '../src/model/schema.js'
import type { CreditTransferDocument } from '../src/model/schema.js'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEBTOR_IBAN = 'DE89370400440532013000'
const CREDITOR_IBAN = 'DE65200400300234567000'
const CREDITOR_ID = 'DE98ZZZ09999999999'

// ---------------------------------------------------------------------------
// Helper: build a pain.001.001.03 XML with the sepa devDependency
// ---------------------------------------------------------------------------

function buildPain001003(): string {
  const doc = new SEPA.Document('pain.001.001.03')
  doc.grpHdr.id = 'COEX-CT-001'
  doc.grpHdr.created = new Date('2026-06-01T08:00:00Z')
  doc.grpHdr.initiatorName = 'Coexistence Test GmbH'

  const info = doc.createPaymentInfo()
  info.requestedExecutionDate = new Date('2026-06-10')
  info.debtorIBAN = DEBTOR_IBAN
  info.debtorBIC = 'COBADEFFXXX'
  info.debtorName = 'Coexistence Test GmbH'

  const tx1 = info.createTransaction()
  tx1.creditorName = 'Supplier One'
  tx1.creditorIBAN = CREDITOR_IBAN
  tx1.amount = 12.34
  tx1.end2endId = 'COEX-E2E-0001'
  // Both transactions need remittanceInfo so sepa does not emit <Ustrd/> (empty element),
  // which would fail the .03 XSD minLength constraint.
  tx1.remittanceInfo = 'Payment COEX/01'

  const tx2 = info.createTransaction()
  tx2.creditorName = 'Supplier Two'
  tx2.creditorIBAN = CREDITOR_IBAN
  tx2.amount = 56.78
  tx2.end2endId = 'COEX-E2E-0002'
  tx2.remittanceInfo = 'Invoice COEX/01'

  info.addTransaction(tx1)
  info.addTransaction(tx2)
  doc.addPaymentInfo(info)

  return doc.toString()
}

// ---------------------------------------------------------------------------
// Helper: minimal valid pain.008.001.02 XML
//
// Element ordering follows PaymentInstructionInformation4 in the .02 XSD:
//   PmtInfId, PmtMtd, PmtTpInf, ReqdColltnDt, Cdtr, CdtrAcct, CdtrAgt (required),
//   CdtrSchmeId, DrctDbtTxInf
//
// Element ordering in DrctDbtTxInf (DirectDebitTransactionInformation9):
//   PmtId, InstdAmt, DrctDbtTx (mandate), DbtrAgt (required), Dbtr, DbtrAcct
// ---------------------------------------------------------------------------

const PAIN008_002_XML = `<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.001.02">
  <CstmrDrctDbtInitn>
    <GrpHdr>
      <MsgId>COEX-DD-001</MsgId>
      <CreDtTm>2026-06-01T08:00:00</CreDtTm>
      <NbOfTxs>1</NbOfTxs>
      <InitgPty><Nm>Coexistence Test GmbH</Nm></InitgPty>
    </GrpHdr>
    <PmtInf>
      <PmtInfId>COEX-DD-BATCH-001</PmtInfId>
      <PmtMtd>DD</PmtMtd>
      <PmtTpInf>
        <SvcLvl><Cd>SEPA</Cd></SvcLvl>
        <LclInstrm><Cd>CORE</Cd></LclInstrm>
        <SeqTp>FRST</SeqTp>
      </PmtTpInf>
      <ReqdColltnDt>2026-07-01</ReqdColltnDt>
      <Cdtr><Nm>Coexistence Test GmbH</Nm></Cdtr>
      <CdtrAcct><Id><IBAN>DE89370400440532013000</IBAN></Id></CdtrAcct>
      <CdtrAgt><FinInstnId><BIC>COBADEFFXXX</BIC></FinInstnId></CdtrAgt>
      <CdtrSchmeId>
        <Id>
          <PrvtId>
            <Othr>
              <Id>DE98ZZZ09999999999</Id>
              <SchmeNm><Prtry>SEPA</Prtry></SchmeNm>
            </Othr>
          </PrvtId>
        </Id>
      </CdtrSchmeId>
      <DrctDbtTxInf>
        <PmtId><EndToEndId>COEX-DD-E2E-0001</EndToEndId></PmtId>
        <InstdAmt Ccy="EUR">25.00</InstdAmt>
        <DrctDbtTx>
          <MndtRltdInf>
            <MndtId>COEX-MAND-001</MndtId>
            <DtOfSgntr>2025-03-15</DtOfSgntr>
          </MndtRltdInf>
        </DrctDbtTx>
        <DbtrAgt><FinInstnId><BIC>DEUTDEDBXXX</BIC></FinInstnId></DbtrAgt>
        <Dbtr><Nm>Debtor Company AG</Nm></Dbtr>
        <DbtrAcct><Id><IBAN>DE65200400300234567000</IBAN></Id></DbtrAcct>
      </DrctDbtTxInf>
    </PmtInf>
  </CstmrDrctDbtInitn>
</Document>`

// ---------------------------------------------------------------------------
// Task 3a: parse pain.001.001.03 generated by sepa library
// ---------------------------------------------------------------------------

describe('coexistence: parse() reads pain.001.001.03 (generated by sepa library)', () => {
  it('returns ok:true with type="pain.001"', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    expect(result.ok, result.ok ? '' : (result as { error: string }).error).toBe(true)
    if (!result.ok) throw new Error('expected ok:true')
    expect(result.type).toBe('pain.001')
  })

  it('returns version="pain.001.001.03"', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    if (!result.ok || result.type !== 'pain.001') throw new Error('expected ok pain.001')
    expect(result.version).toBe('pain.001.001.03')
  })

  it('messageId round-trips correctly', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    if (!result.ok || result.type !== 'pain.001') throw new Error('expected ok pain.001')
    expect(result.data.messageId).toBe('COEX-CT-001')
  })

  it('initiatingParty round-trips correctly', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    if (!result.ok || result.type !== 'pain.001') throw new Error('expected ok pain.001')
    expect(result.data.initiatingParty).toBe('Coexistence Test GmbH')
  })

  it('executionDate is YYYY-MM-DD (plain text in .03, not wrapped in Dt)', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    if (!result.ok || result.type !== 'pain.001') throw new Error('expected ok pain.001')
    expect(result.data.batches).toHaveLength(1)
    expect(result.data.batches[0]?.executionDate).toBe('2026-06-10')
  })

  it('debtor IBAN is preserved', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    if (!result.ok || result.type !== 'pain.001') throw new Error('expected ok pain.001')
    expect(result.data.batches[0]?.debtor.iban).toBe(DEBTOR_IBAN)
  })

  it('debtor BIC is preserved (sepa library uses <BIC> not <BICFI>)', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    if (!result.ok || result.type !== 'pain.001') throw new Error('expected ok pain.001')
    expect(result.data.batches[0]?.debtor.bic).toBe('COBADEFFXXX')
  })

  it('both transfers have correct endToEndIds', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    if (!result.ok || result.type !== 'pain.001') throw new Error('expected ok pain.001')
    const transfers = result.data.batches[0]?.transfers
    expect(transfers).toHaveLength(2)
    expect(transfers?.[0]?.endToEndId).toBe('COEX-E2E-0001')
    expect(transfers?.[1]?.endToEndId).toBe('COEX-E2E-0002')
  })

  it('amounts are correct as Money minorUnits', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    if (!result.ok || result.type !== 'pain.001') throw new Error('expected ok pain.001')
    const transfers = result.data.batches[0]?.transfers
    // 12.34 EUR = 1234 minor units
    expect(transfers?.[0]?.amount.minorUnits).toBe(1234n)
    expect(transfers?.[0]?.amount.currencyCode).toBe('EUR')
    // 56.78 EUR = 5678 minor units
    expect(transfers?.[1]?.amount.minorUnits).toBe(5678n)
  })

  it('creditor IBANs are preserved', () => {
    const xml = buildPain001003()
    const result = parse(xml)
    if (!result.ok || result.type !== 'pain.001') throw new Error('expected ok pain.001')
    const transfers = result.data.batches[0]?.transfers
    expect(transfers?.[0]?.creditor.iban).toBe(CREDITOR_IBAN)
    expect(transfers?.[1]?.creditor.iban).toBe(CREDITOR_IBAN)
  })
})

// ---------------------------------------------------------------------------
// Task 3b: pain.008.001.02 XSD validation first, then parse
// ---------------------------------------------------------------------------

describe('coexistence: pain.008.001.02 hand-built fixture validates against XSD', () => {
  it('fixture validates as valid=true against the .02 XSD (oracle)', async () => {
    const result = await validateXsd(PAIN008_002_XML)
    expect(result.errors).toHaveLength(0)
    expect(result.valid).toBe(true)
  })
})

describe('coexistence: parse() reads pain.008.001.02', () => {
  it('returns ok:true with type="pain.008"', () => {
    const result = parse(PAIN008_002_XML)
    expect(result.ok, result.ok ? '' : (result as { error: string }).error).toBe(true)
    if (!result.ok) throw new Error('expected ok:true')
    expect(result.type).toBe('pain.008')
  })

  it('returns version="pain.008.001.02"', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    expect(result.version).toBe('pain.008.001.02')
  })

  it('messageId is correct', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    expect(result.data.messageId).toBe('COEX-DD-001')
  })

  it('initiatingParty is correct', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    expect(result.data.initiatingParty).toBe('Coexistence Test GmbH')
  })

  it('creditorId is extracted from CdtrSchmeId/Id/PrvtId/Othr/Id', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    expect(result.data.creditor.creditorId).toBe(CREDITOR_ID)
  })

  it('creditor IBAN is preserved', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    expect(result.data.creditor.iban).toBe(DEBTOR_IBAN)
  })

  it('creditor BIC is preserved (legacy <BIC> element)', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    expect(result.data.creditor.bic).toBe('COBADEFFXXX')
  })

  it('sequenceType is FRST', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    expect(result.data.batches[0]?.sequenceType).toBe('FRST')
  })

  it('collectionDate is 2026-07-01', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    expect(result.data.batches[0]?.collectionDate).toBe('2026-07-01')
  })

  it('mandate id is correct', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    const collection = result.data.batches[0]?.collections[0]
    expect(collection?.mandate.id).toBe('COEX-MAND-001')
    expect(collection?.mandate.signatureDate).toBe('2025-03-15')
  })

  it('debtor IBAN is preserved', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    const collection = result.data.batches[0]?.collections[0]
    expect(collection?.debtor.iban).toBe(CREDITOR_IBAN)
  })

  it('amount is 25.00 EUR (2500 minorUnits)', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    const collection = result.data.batches[0]?.collections[0]
    expect(collection?.amount.minorUnits).toBe(2500n)
    expect(collection?.amount.currencyCode).toBe('EUR')
  })

  it('endToEndId is correct', () => {
    const result = parse(PAIN008_002_XML)
    if (!result.ok || result.type !== 'pain.008') throw new Error('expected ok pain.008')
    const collection = result.data.batches[0]?.collections[0]
    expect(collection?.endToEndId).toBe('COEX-DD-E2E-0001')
  })
})

// ---------------------------------------------------------------------------
// Task 3c: validateXsd handles all four namespaces
// ---------------------------------------------------------------------------

describe('coexistence: validateXsd handles all four namespaces', () => {
  it('validates a pain.001.001.03 document as valid=true', async () => {
    const xml = buildPain001003()
    const result = await validateXsd(xml)
    expect(result.errors).toHaveLength(0)
    expect(result.valid).toBe(true)
  })

  it('validates a pain.008.001.02 document as valid=true', async () => {
    const result = await validateXsd(PAIN008_002_XML)
    expect(result.valid).toBe(true)
  })

  it('validates a pain.001.001.09 document (write target) as valid=true', async () => {
    const doc: CreditTransferDocument = {
      messageId: 'COEX-VALIDATE-001',
      createdAt: '2026-06-01T08:00:00Z',
      initiatingParty: 'Test GmbH',
      batches: [
        {
          id: 'BATCH-001',
          executionDate: '2026-06-10',
          debtor: { name: 'Test GmbH', iban: DEBTOR_IBAN },
          transfers: [
            {
              endToEndId: 'E2E-0001',
              amount: euros('1.00'),
              creditor: { name: 'Recipient', iban: CREDITOR_IBAN },
            },
          ],
        },
      ],
    }
    const xml = writeCreditTransfer(doc)
    const result = await validateXsd(xml)
    expect(result.valid, `XSD errors: ${result.errors.join(', ')}`).toBe(true)
  })

  it('returns valid=false with descriptive error for an unknown namespace', async () => {
    const xml = `<?xml version="1.0"?><Document xmlns="urn:example:unknown"><SomeEl/></Document>`
    const result = await validateXsd(xml)
    expect(result.valid).toBe(false)
    expect(result.errors[0]).toMatch(/Unsupported namespace/i)
  })

  it('returns valid=false with descriptive error when xmlns is missing', async () => {
    const xml = `<?xml version="1.0"?><Document><SomeEl/></Document>`
    const result = await validateXsd(xml)
    expect(result.valid).toBe(false)
    expect(result.errors[0]).toMatch(/Could not detect/i)
  })
})
