/**
 * Cross-implementation parser fixtures.
 *
 * These XML files were produced by other open-source SEPA libraries (see
 * test/fixtures/external/NOTICE.md for sources and licenses). Parsing them proves
 * our parser reads real-world XML generated by independent tools, not only our own
 * writer output, and that such input survives our full pipeline:
 *   parse -> business validation -> re-write -> XSD validation.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from '../src/parser/parser.js'
import { validateCreditTransfer } from '../src/model/validate.js'
import { writeCreditTransfer } from '../src/writer/writer.js'
import { validateXsd } from '../src/xsd.js'
import type { CreditTransferVariant } from '../src/writer/writer.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SEPA_KING_DIR = join(__dirname, 'fixtures/external/sepa_king')

function readFixture(name: string): string {
  return readFileSync(join(SEPA_KING_DIR, name), 'utf8')
}

describe('External fixtures: sepa_king (MIT) credit transfers', () => {
  const cases: Array<{ file: string; variant: CreditTransferVariant }> = [
    { file: 'pain.001.001.03.xml', variant: 'pain.001.001.03' },
    { file: 'pain.001.003.03.xml', variant: 'pain.001.003.03' },
  ]

  for (const { file, variant } of cases) {
    describe(file, () => {
      it('parses to a pain.001 credit transfer document', () => {
        const result = parse(readFixture(file))
        expect(result.ok).toBe(true)
        if (!result.ok) throw new Error('expected parse success')
        expect(result.type).toBe('pain.001')
        expect(result.data.batches.length).toBeGreaterThanOrEqual(1)
        const firstBatch = result.data.batches[0]!
        expect(firstBatch.transfers.length).toBeGreaterThanOrEqual(1)
        expect(firstBatch.transfers[0]!.amount.currencyCode).toBe('EUR')
      })

      it('the parsed model passes our business validation', () => {
        const result = parse(readFixture(file))
        if (!result.ok) throw new Error('expected parse success')
        const validated = validateCreditTransfer(result.data)
        expect(validated.ok).toBe(true)
      })

      it('survives a full round-trip: parse -> re-write -> XSD valid', async () => {
        const result = parse(readFixture(file))
        if (!result.ok) throw new Error('expected parse success')
        const rewritten = writeCreditTransfer(result.data, { variant })
        const xsd = await validateXsd(rewritten)
        expect(xsd.valid, `XSD errors: ${xsd.errors.join(', ')}`).toBe(true)
      })
    })
  }
})
