/**
 * Cross-implementation parser fixtures.
 *
 * These XML files were produced by other open-source SEPA libraries (see
 * test/fixtures/external/NOTICE.md for sources and licenses). Parsing them proves
 * our parser reads real-world XML generated by independent tools, not only our own
 * writer output, and that such input survives our full pipeline:
 *   parse -> business validation -> re-write -> XSD validation.
 *
 * Some fixtures are from non-SEPA or template sources and are expected to fail our
 * parser with specific, documented errors. These tests pin the exact rejection reason
 * so regressions surface immediately.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from '../src/parser/parser.js'
import { validateCreditTransfer } from '../src/model/validate.js'
import { writeCreditTransfer } from '../src/writer/writer.js'
import { validateXsd } from '../src/xsd.js'
import type { CreditTransferVariant } from '../src/writer/writer.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SEPA_KING_DIR = join(__dirname, 'fixtures/external/sepa_king')
const ISO20022NET_DIR = join(__dirname, 'fixtures/external/iso20022net')
const PAIN001_DIR = join(__dirname, 'fixtures/external/pain001')

function readFixture(dir: string, name: string): string {
  return readFileSync(join(dir, name), 'utf8')
}

describe('External fixtures: sepa_king (MIT) credit transfers', () => {
  const cases: Array<{ file: string; variant: CreditTransferVariant }> = [
    { file: 'pain.001.001.03.xml', variant: 'pain.001.001.03' },
    { file: 'pain.001.003.03.xml', variant: 'pain.001.003.03' },
  ]

  for (const { file, variant } of cases) {
    describe(file, () => {
      it('parses to a pain.001 credit transfer document', () => {
        const result = parse(readFixture(SEPA_KING_DIR, file))
        expect(result.ok).toBe(true)
        if (!result.ok) throw new Error('expected parse success')
        expect(result.type).toBe('pain.001')
        expect(result.data.batches.length).toBeGreaterThanOrEqual(1)
        const firstBatch = result.data.batches[0]!
        expect(firstBatch.transfers.length).toBeGreaterThanOrEqual(1)
        expect(firstBatch.transfers[0]!.amount.currencyCode).toBe('EUR')
      })

      it('the parsed model passes our business validation', () => {
        const result = parse(readFixture(SEPA_KING_DIR, file))
        if (!result.ok) throw new Error('expected parse success')
        const validated = validateCreditTransfer(result.data)
        expect(validated.ok).toBe(true)
      })

      it('survives a full round-trip: parse -> re-write -> XSD valid', async () => {
        const result = parse(readFixture(SEPA_KING_DIR, file))
        if (!result.ok) throw new Error('expected parse success')
        const rewritten = writeCreditTransfer(result.data, { variant })
        const xsd = await validateXsd(rewritten)
        expect(xsd.valid, `XSD errors: ${xsd.errors.join(', ')}`).toBe(true)
      })
    })
  }
})

// ---------------------------------------------------------------------------
// Iso20022Net fixtures (MIT)
// ---------------------------------------------------------------------------

describe('External fixtures: Iso20022Net (MIT)', () => {
  /**
   * The Iso20022Net pain.001.001.03 sample is an illustrative ISO standard example,
   * not a SEPA payment file. Account parties use proprietary Othr/Id account numbers
   * rather than IBAN, and currencies include JPY and USD. Our parser requires IBAN for
   * debtor and creditor parties, so extraction fails at the payment batch level with a
   * documented, stable error. The test pins this exact behavior so any regression
   * (e.g. a change that silently drops the non-IBAN account) surfaces immediately.
   */
  it('rejects the Iso20022Net MIT pain.001.001.03 non-IBAN sample with a documented error', () => {
    const xml = readFixture(ISO20022NET_DIR, 'pain.001.001.03.xml')
    const result = parse(xml)
    expect(result.ok).toBe(false)
    if (result.ok) throw new Error('expected parse failure for non-IBAN non-SEPA sample')
    // The debtor account uses Othr/Id (no IBAN), so extractPaymentBatch returns null.
    expect(result.error).toBe('Failed to extract PaymentBatch from PmtInf')
  })

  /**
   * The Iso20022Net pain.008.001.02 sample is an ISO standard illustration using
   * proprietary account numbers (no IBAN) and USD amounts. Our parser requires IBAN
   * for the pain.008 creditor account, so extraction fails at the creditor level.
   * This pins the exact rejection so any silent-drop regression surfaces.
   */
  it('rejects the Iso20022Net MIT pain.008.001.02 non-IBAN sample with a documented error', () => {
    const xml = readFixture(ISO20022NET_DIR, 'pain.008.001.02.xml')
    const result = parse(xml)
    expect(result.ok).toBe(false)
    if (result.ok) throw new Error('expected parse failure for non-IBAN non-SEPA sample')
    // The creditor account uses Othr/Id (no IBAN), so extractCreditorFromPmtInf returns null.
    expect(result.error).toBe('Failed to extract Creditor from first PmtInf')
  })
})

// ---------------------------------------------------------------------------
// pain001 (Apache-2.0) fixtures
// ---------------------------------------------------------------------------

describe('External fixtures: pain001 (Apache-2.0)', () => {
  /**
   * The pain001 pain.001.001.09 template file uses IBANs that fail the ISO 7064
   * MOD 97-10 checksum (they are placeholder values, not real account numbers).
   * This is documented in NOTICE.md. Our parser reaches the Zod model validation
   * step, which correctly rejects the file. The test pins the exact error prefix,
   * confirming our mod-97 check is active and functioning for externally-sourced files.
   * NbOfTxs=2 but the file has 5 transactions (header inconsistency in the template),
   * which our parser does not check on the read path.
   */
  it('rejects the pain001 Apache-2.0 pain.001.001.09 template due to invalid IBAN checksums', () => {
    const xml = readFixture(PAIN001_DIR, 'pain.001.001.09.xml')
    const result = parse(xml)
    expect(result.ok).toBe(false)
    if (result.ok) throw new Error('expected parse failure for template with invalid IBANs')
    // Parser reaches Zod validation; debtor and all creditor IBANs fail mod-97.
    expect(result.error).toMatch(/^Model validation failed after parse:/)
    expect(result.error).toContain('IBAN failed mod-97 checksum validation')
    // Confirm exactly how many IBAN failures are reported (1 debtor + 5 creditors = 6 total)
    const matches = result.error.match(/IBAN failed mod-97 checksum validation/g)
    expect(matches?.length).toBe(6)
  })
})
